### PR TITLE
Fix display being blank

### LINKED ISSUE #1: Not getting anything graphical at all
I'm aware that there is no springboard support as of yet but I don't see the restore progress bar onscreen. And on the original project you were supposed to be able to see the bar.

### PR DESCRIPTION
**Pull request by chris-pcguy**
Fixes #1

### CODE REVIEW

**Comment by ChefKissInc** [comment]
I have some local changes I've not committed yet, 1 sec

**Comment by ChefKissInc** [comment]
@chris-pcguy I've pushed those changes, please rebase your PR

File: hw/arm/t8030.c [hunk 1]
```diff
@@ -1737,6 +1737,8 @@ static void t8030_machine_init(MachineState *machine)
     assert(set_dtb_prop(child, "graphics-featureset-class", 7, "MTL1,2"));
     assert(set_dtb_prop(child, "graphics-featureset-fallbacks", 15, "MTL1,2:GLES2,0"));
     assert(set_dtb_prop(tms->device_tree, "target-type", 4, "sim")); // TODO: implement PMP
+    data = 1;
```
Comment (ChefKissInc) [inline hw/arm/t8030.c:1740]:
```diff
- data = 1;
+ data = 0;
```
Please change this to 0 in order to use a black background and not a white one.

File: hw/display/apple_h12p.c [hunk 2]
```diff
@@ -205,11 +221,24 @@ static void h12p_gfx_update(void *opaque)
...
+                return;
+            }
+        }
 
         uint8_t *dest = surface_data(surface);
         for (size_t i = 0; i < s->height; i++) {
-            h12p_draw_row(s, dest, buf + i * stride, s->width, 0);
-            dest += stride;
+            //h12p_draw_row(s, dest, buf + i * stride, s->width, 0);
+            //dest += stride;
```
Comment (ChefKissInc) [inline hw/display/apple_h12p.c:238]: Remove these comments.

File: hw/display/apple_h12p.c [hunk 3]
```diff
@@ -243,8 +272,12 @@ static const VMStateDescription vmstate_apple_h12p = {
...
 
 static Property apple_h12p_props[] = {
-    DEFINE_PROP_UINT32("width", AppleH12PState, width, 480),
-    DEFINE_PROP_UINT32("height", AppleH12PState, height, 680),
+    // iPhone 4/4S
+    DEFINE_PROP_UINT32("width", AppleH12PState, width, 640),
+    DEFINE_PROP_UINT32("height", AppleH12PState, height, 960),
+    // iPhone 11
+    //DEFINE_PROP_UINT32("width", AppleH12PState, width, 828),
+    //DEFINE_PROP_UINT32("height", AppleH12PState, height, 1792),
```
Comment (ChefKissInc) [inline hw/display/apple_h12p.c:280]: Is this really required? It works with the old resolution value too.

Screenshot 2023-07-10 at 21 51 46

File: target/arm/helper.c [hunk 4]
```diff
@@ -11093,7 +11093,7 @@ static CPUARMTBFlags rebuild_hflags_a64(CPUARMState *env, int el, int fp_el,
          * The decision of which action to take is left to a helper.
          */
         if (sctlr & (SCTLR_EnIA | SCTLR_EnIB | SCTLR_EnDA | SCTLR_EnDB)) {
-            DP_TBFLAG_A64(flags, PAUTH_ACTIVE, 1);
+            //DP_TBFLAG_A64(flags, PAUTH_ACTIVE, 1);
```
Comment (ChefKissInc) [inline target/arm/helper.c:11096]: Why?

File: target/arm/ptw.c [hunk 5]
```diff
@@ -438,6 +438,7 @@ static inline int
 pte_to_sprr_prot_is_guarded(CPUARMState *env, int ap, int xn, int pxn, bool guarded)
 {
     int sprr_idx = ((ap << 2) | (xn << 1) | pxn) & 0xf;
+    assert(arm_current_el(env) < 2);
```
Comment (ChefKissInc) [inline target/arm/ptw.c:441]: Why?

File: hw/arm/t8030.c [hunk 6]
```diff
@@ -105,7 +105,7 @@
 #define T8030_SIO_DATA_SIZE     (0xf8000)
 #define T8030_SIO_DATA_REMAP    (0x220000)
 
-#define T8030_PANIC_BASE        (0x8ffeb0000)
+#define T8030_PANIC_BASE        (0x8fc2b4000)
```
Comment (ChefKissInc) [inline hw/arm/t8030.c:108]: Why?

**Review by ChefKissInc — CHANGES_REQUESTED** [review]

File: target/arm/helper.c (hunk 4 above)
Comment (chris-pcguy) [reply target/arm/helper.c:11096]: PAC might crash with a nullpointer called 0x02000000 or something like that otherwise.

File: hw/arm/t8030.c (hunk 6 above)
Comment (chris-pcguy) [reply hw/arm/t8030.c:108]: To accomodate the risen vram size, so it won't overlap.

File: hw/arm/t8030.c (hunk 1 above)
Comment (chris-pcguy) [reply hw/arm/t8030.c:1740]: Okay. I just took the value, my iPad printed.

File: hw/display/apple_h12p.c (hunk 2 above)
Comment (chris-pcguy) [reply hw/display/apple_h12p.c:238]: m'kay.

File: hw/display/apple_h12p.c (hunk 3 above)
Comment (chris-pcguy) [reply hw/display/apple_h12p.c:280]: According to a google search I made a week ago, having a value there that makes libMobileGestalt complain will result e.g. in crashing apps.
So I guess it would be best to set it to a value, which is expected by libMobileGestalt.

**Comment by chris-pcguy** [comment]
That might be because of your last-minute changes.

File: target/arm/helper.c (hunk 4 above)
Comment (ChefKissInc) [reply target/arm/helper.c:11096]: Eh?

File: target/arm/ptw.c (hunk 5 above)
Comment (chris-pcguy) [reply target/arm/ptw.c:441]: That's the reason:
uint64_t sprr_el_br_el1[4][2];

A security measure to prevent it overflowing.

**Comment by ChefKissInc** [comment]
> That might be because of your last-minute changes.

Reverted them, and that still happens. It is likely the code continuing to read from the DART even though USB recovery timed out and a shutdown commenced

File: hw/display/apple_h12p.c (hunk 2 above)
Comment (chris-pcguy) [reply hw/display/apple_h12p.c:238]: Just didn't wanted to remove your code.

File: target/arm/helper.c (hunk 4 above)
Comment (chris-pcguy) [reply target/arm/helper.c:11096]: Something in Apple's IOMFB might be somehow incompatible with PAC.
It crashed way too often, so I just disabled PAC.
I'll revert it.
If it continues to prone to crash, you can disable PAC.

**Comment by chris-pcguy** [comment]
Ah, yes, sorry. I recognize it now. Shutting down iOS or failing to allocate DART planes sets the planes to incompatible legacy values.
I've fully fixed that in a private branch. Will transfer these changes.

File: target/arm/helper.c (hunk 4 above)
Comment (ChefKissInc) [reply target/arm/helper.c:11096]: I've not experienced that here, but I'm not booting the installed OS cause I've not gotten to installing iOS again yet

**Comment by ChefKissInc** [comment]
Here's the register log up to, including, the crash
[RegisterLog.txt](https://github.com/ChefKissInc/qemu-t8030/files/12005900/RegisterLog.txt)

File: hw/display/apple_h12p.c (hunk 2 above)
Comment (ChefKissInc) [reply hw/display/apple_h12p.c:238]: It's fine; Git has a change history, lol

**Comment by chris-pcguy** [comment]
Good enough?

File: hw/arm/t8030.c (hunk 6 above)
Comment (chris-pcguy) [reply hw/arm/t8030.c:108]: *accommodate

**Review by chris-pcguy — COMMENTED** [review]
.
Edit: Damn, the "Changes requested" message won't disappear.

**Comment by ChefKissInc** [comment]
Seems to work fine now

Screenshot 2023-07-10 at 23 16 38

**Review by ChefKissInc — APPROVED** [review]

**Comment by ChefKissInc** [comment]
Actually, @chris-pcguy, I think it might not be using both planes? I think it switches between them

**Comment by ChefKissInc** [comment]
Screenshot 2023-07-10 at 23 20 17
Two `GenPipe`s

**Comment by ChefKissInc** [comment]
Screenshot 2023-07-10 at 23 20 46

and

**Comment by ChefKissInc** [comment]
Screenshot 2023-07-10 at 23 21 28

**Comment by ChefKissInc** [comment]
I mean for the drawing

Screenshot 2023-07-10 at 23 26 42

**Comment by chris-pcguy** [comment]
Did I missed something? Should something be changed?
If I can find an occasion, where plane1 is used completely independent, I can look for another workaround to prevent errors on shutdown.

**Comment by chris-pcguy** [comment]
I rather saw it as one GenPipe with two planes, instead of two GenPipes with one plane each.
I don't know if there would be a difference if it would be treated one way or another.
Jacke wie Hose.

**Comment by ChefKissInc** [comment]
```c
size_t size = 0;
g_autofree uint8_t *buf = NULL;
if (s->genpipe1_plane_start && s->genpipe1_plane_end && s->genpipe1_plane_stride && s->genpipe0_plane_stride) {
    size = s->genpipe1_plane_end - s->genpipe1_plane_start;
    buf = g_malloc(size);
    if (dma_memory_read(&s->dma_as, s->genpipe1_plane_start, buf, size, MEMTXATTRS_UNSPECIFIED) != MEMTX_OK) {
        error_report("[H12P] Failed to read GenPipe1 plane");
        return;
    }
} else if (s->genpipe0_plane_start && s->genpipe0_plane_end && s->genpipe0_plane_stride) {
    size = s->genpipe0_plane_end - s->genpipe0_plane_start;
    buf = g_malloc(size);
    if (dma_memory_read(&s->dma_as, s->genpipe0_plane_start, buf, size, MEMTXATTRS_UNSPECIFIED) != MEMTX_OK) {
        error_report("[H12P] Failed to read GenPipe0 plane");
        return;
    }
}

uint8_t *dest = surface_data(surface);
for (size_t i = 0; i < s->height; i++) {
    h12p_draw_row(s, dest + i * stride, buf + i * stride, s->width, 0);
}
```

@chris-pcguy maybe this is more correct?

**Comment by ChefKissInc** [comment]
I've not looked into it enough to know for sure though

**Comment by chris-pcguy** [comment]
Wouldn't that lead to the foreground being overwritten with the background?

**Comment by ChefKissInc** [comment]
It draws the plane from genpipe 1 if it exists, otherwise the genpipe 0 plane. Seems to work fine for me

**Comment by chris-pcguy** [comment]
But what if both exists?

**Comment by ChefKissInc** [comment]
And according to the logs it did GenPipe 0 -> GenPipe 1 -> GenPipe 0

**Comment by chris-pcguy** [comment]
I tested it with a white background and something I deemed equivalent:
"""
if (size1 && buf1 != NULL)
    h12p_draw_row(s, dest + i * stride, buf1 + i * stride, s->width, 0);
else if (size0 && buf0 != NULL)
    h12p_draw_row(s, dest + i * stride, buf0 + i * stride, s->width, 0);
"""
I feared that it would break something, but it looks exactly the same.
Will change it to your example.

**Comment by ChefKissInc** [comment]
Actually, I think you might be right? But then still we're overwriting the background with the foreground right now

**Comment by chris-pcguy** [comment]
> But then still we're overwriting the background with the foreground right now

Isn't that the industry standard?
I did it now just like in your example and it still looks the same.
I have an idea, let's have both with "#if"/"#endif"

**Comment by ChefKissInc** [comment]
@chris-pcguy Transparency. If there’s a bunch of stuff on foreground and then a full screen image on background then the empty pixels on the foreground would show as black

**Comment by chris-pcguy** [comment]
Ahh, the famous alpha channel. Is there already code for combining multiple image layers in Qemu or should be borrow it from some source like Firefox?

**Comment by ChefKissInc** [comment]
@chris-pcguy Idk, only one way to find out

**Comment by chris-pcguy** [comment]
I have an idea. We keep it as it is right now and handle the "transparent window, picture background"-usecase when we implement stuff like x-y offsets.

**Comment by ChefKissInc** [comment]
> Edit: SpringBoard doesn't work yet.

What happens with it?

**Comment by chris-pcguy** [comment]
It looks like booting a live system will result in the system using PIODMA. Either we could handle that as well or we should figure out how to convince iOS to not use it.

**Comment by ChefKissInc** [comment]
What's PIODMA?

**Comment by chris-pcguy** [comment]
Might stand for Parallel IO DMA, has its own mapper "mapper-disp0-piodma".
Afaik a fallback in case that a iommu_alloc fails.

**Comment by ChefKissInc** [comment]
What happens if you comment out the default case for the register read handler

**Comment by chris-pcguy** [comment]
I've tested it with a live system, not with a ramdisk.
I'm not sure what that should change.
I can't see any difference, the vram dumps only contains zeroes.

**Comment by ChefKissInc** [comment]
@chris-pcguy It would always return 0 for the registers we don’t handle. Maybe it would change the flow.
Btw, sorry to ask again, but could we discuss this somewhere better like on Telegram? Please :) ?

**Comment by chris-pcguy** [comment]
I can't find your email address right now. Can you send your telegram nickname to me?

**Comment by ChefKissInc** [comment]
@chris-pcguy My handle is @ChefKissInc like my GitHub profile lol

**Comment by chris-pcguy** [comment]
Took me a google search to find out how to use Telegram with only usernames, didn't even had one. I mostly use Signal.
